import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "@/components/ui/toast";
import MySession from "@/components/MySession/MySession";
import Footer from "@/components/Footer/Footer";

const inter = Exo({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "fresh cart",
  description: "Generated by create mohamed",
};

// src/app/layout.tsx

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn("antialiased", "font-sans", inter.variable)}>
      {/* Add suppressHydrationWarning here */}
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <MySession>
          <Navbar />
          {children}
          <Toaster />
          
          <Footer/>
        </MySession>
      </body>
    </html>
  );
}
